# Base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port for the FastAPI web app
EXPOSE 443

# Default command to run the FastAPI web app
CMD ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "433"]
