services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: fastapi_web
    command: uvicorn run:app --host 0.0.0.0 --port 443
    ports:
      - "443:443"
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://<your_db_username>:<your_db_password>@postgres:5432/<your_db_name>
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: celery_worker
    command: celery -A app.celery_init.celery worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://<your_db_username>:<your_db_password>@postgres:5432/<your_db_name>
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: celery_beat
    command: celery -A app.celery_init.celery beat --loglevel=info --pool=solo
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://<your_db_username>:<your_db_password>@postgres:5432/<your_db_name>
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: <your_db_name>
      POSTGRES_USER: <your_db_username>
      POSTGRES_PASSWORD: <your_db_password>
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: