services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ss
    container_name: fastapi_web
    command: uvicorn app.__init__:create_app --factory --host 0.0.0.0 --port 443
    ports:
      - "443:443"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./model:/app/model
      - ./data:/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
  
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./model:/app/model
      - ./data:/app/data
    user: "1000:1000"  
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
